# Generated by Django 4.2.1 on 2023-05-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=85.0, max_digits=4)),
                ('date', models.DateField(auto_now=True)),
                ('stock', models.IntegerField(default=50, help_text='How many items are currentl;y in stock')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='Stock keeping Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
            ],
        ),
    ]
