# Generated by Django 4.2.1 on 2023-05-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_digitalproduct_physicalproduct_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='digitalproduct',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='physicalproduct',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
